### ISSUE TITLE
node positions are lost after rehype-raw

### ISSUE THREAD

**Issue by ruifortes** [rehypejs/rehype-raw#9] opened 2018-04-20 22:04 UTC
Hello.
After using rehype-ray all nodes position is blanked.
position.start and position.end are set no an empty object
Is this a bug?

**Comment by wooorm** [comment] 2018-05-11 10:39
How are you using it? I don’t believe that should happen?

**Comment by wooorm** [comment] 2018-06-24 21:58
Closing for now. If it’s still an issue, could you send more info?

**Closed by wooorm** 2018-06-24 21:58 UTC

**Comment by felixfbecker** [comment] 2021-07-18 09:58
I am facing the same issue. I am trying to parse markdown with embedded HTML for linting purposes and need an actual AST of the HTML, not just the markdown.

When using just `remark` and `rehype`, all AST nodes still have position information:

```ts
const processor = unified()
		.use(remarkFrontmatter)
		.use(remarkParse)
		.use(remarkToRehype, { allowDangerousHtml: true })
const rootNode = processor.parse(content)
const result = await processor.run(rootNode)
console.log(result.position) // { start: ..., end: ... }
```

However, as we all know, without `rehype-raw` I don't have AST nodes for the embedded HTML besides the `raw` nodes.

But as soon as I add `remark-raw` to the mix, there is no source position anymore:

```ts
const processor = unified()
		.use(remarkFrontmatter)
		.use(remarkParse)
		.use(remarkToRehype, { allowDangerousHtml: true })
		.use(rehypeRaw)
const rootNode = processor.parse(content)
const result = await processor.run(rootNode)
console.log(result.position) // undefined
```

**Comment by wooorm** [comment] 2021-07-18 10:03
The problem is that rehype raw needs to have a virtual file with contents to work.
Because you’re splitting the process, and not passing one to `run`, it doesn’t work:

```js
const file = new VFile(content)
const rootNode = processor.parse(file)
const result = await processor.run(rootNode, file)
```

**Comment by felixfbecker** [comment] 2021-07-18 15:09
So with your snippet above it should work, you say?

**Comment by wooorm** [comment] 2021-07-18 15:11
correct.

**Comment by AhmedBHameed** [comment] 2022-08-10 17:21
Maybe this is also related?

I'm using [react-markdown] with `rehype-raw` as a plugin.

I lost code snippet metatags after using the plugin.

Before using the plugin

![issue](https://user-images.githubusercontent.com/25675361/183975432-8c8e1cfa-3d06-413e-b313-ce8d8d33b4ce.jpg)

After using the plugin

![issue0](https://user-images.githubusercontent.com/25675361/183976301-5a18de8d-fe9f-445e-b0eb-fa92913f39b0.jpg)


**package.json**

```json
    "rehype-raw": "^6.1.1",
    "react-markdown": "8.0.3",
```

Markdown sample used

```markdown
	  ```tsx {1, 3-10} [src/components/SupportLink/SupportLink.tsx]
	  import {useCallback} from 'react';
	  import {useTranslation} from 'react-i18next';
	  import config from '../../config/config';
	  
	  const SupportLink = () => {
	    const {t, i18n} = useTranslation();
	  
	    const changeLanguageHandler = useCallback(() => {
	      if (i18n.language === 'en') {
	        i18n.changeLanguage('de');
	      } else {
	        i18n.changeLanguage('en');
	      }
	    }, [i18n]);
	  
	    const googleSearchLink =
	      i18n.language === 'de'
	        ? config.deGoogleSearchLink
	        : config.enGoogleSearchLink;
	  
	    return (
	      <div>
	        <button onClick={changeLanguageHandler}>
	          {t('changeLanguageLabel')}
	        </button>
	  
	        <a
	          className="testing-link"
	          data-testid="support-link"
	          href={googleSearchLink}
	        >
	          {t('supportLink')}
	        </a>
	      </div>
	    );
	  };
	  
	  export default SupportLink;
	  ```
```

**Comment by JounQin** [comment] 2022-08-10 17:26
@AhmedBHameed A minimal but runnable reproduction is required.

**Comment by AhmedBHameed** [comment] 2022-08-10 19:07
@JounQin 

I was trying to do it via codesandbox but it does not work properly. So here is a repo for a minimal reproduction.
https://github.com/AhmedBHameed/next-rehype-raw-issue

To run it:

- `yarn`
- `yarn build`
- `yarn dev`

You should see 2 versions which show the difference.

Also thanks for you support in advance.

**Comment by wooorm** [comment] 2022-08-10 19:25
This issue is about positional info. Your question is not about positional info. Your screenshot shows positional info is fine.

This issue is also solved, for four years already. **I’ll lock this and hide the new comments to respect previous contributors and to help future googlers find answers**.

Your question is about data. That question is a duplicate of https://github.com/syntax-tree/hast-util-raw/issues/13.
